name: Daily A-share Market Data
on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 1 * * 1-5"
jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run indices fetch
        run: python scripts/fetch_a_indices.py
      - name: Run holdings & flows fetch
        run: python scripts/fetch_holdings_and_flows.py
      - name: Add .nojekyll
        run: |
          mkdir -p docs
          touch docs/.nojekyll
      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update market data" || echo "Nothing to commit"
          git push
